spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 108512
    url: jdbc:mysql://localhost:3306/webchat-order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
#    默认数据库是下划线,Java类是驼峰. 如果不想这样就做如下更改
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl